<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function findTopTags()
    {
        $tags = $this->getEntityManager()->getRepository('AppBundle:Tag')
            ->createQueryBuilder('t')
            ->groupBy('t.hashTag')
            ->setMaxResults(10)
            ->getQuery()
            ->getResult();

        usort($tags, function ($a, $b) {
            if (COUNT($a->getPost()) == COUNT($b->getPost())) {
                return 0;
            }

            return (COUNT($a->getPost()) > COUNT($b->getPost())) ? -1 : 1;
        });

        return $tags;
    }

    public function getLastTags($count)
    {
        $tags = $this->getEntityManager()->getRepository('AppBundle:Tag')
            ->createQueryBuilder('t')
            ->orderBy('t.id', 'DESC')
            ->setMaxResults($count)
            ->getQuery()
            ->getResult();

        return $tags;
    }

    public function getHastTags()
    {
        return $this->getEntityManager()
            ->getRepository('AppBundle:Tag')
            ->createQueryBuilder('t')
            ->select('t.hashTag')
            ->getQuery()
            ->getResult();
    }
}
