app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

app_how_to_load:
    pattern: /how_to_load
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'AppBundle:Static:how_to_load.html.twig'
        maxAge:       86400
        sharedMaxAge: 86400

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app_redmine:
    type: rest
    resource: "@AppBundle/Controller/ApiRedmineController.php"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"