app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app_redmine:
    type: rest
    resource: "@AppBundle/Controller/ApiRedmineController.php"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_photo:
    pattern:  /photo/
    defaults: { _controller: AppBundle:Photo:index }