app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

user_routing:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /

app_how_to_load:
    pattern: /how_to_load
    defaults:
        _controller:  FrameworkBundle:Template:template
        template:     'AppBundle:Static:how_to_load.html.twig'
        maxAge:       86400
        sharedMaxAge: 86400

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app_redmine:
    type: rest
    resource: "@AppBundle/Controller/ApiRedmineController.php"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login